#!/usr/bin/env python3
"""
Convert existing dual-source labels into configurable object-pair labels.

This script DOES NOT recompute labels.
It reads summary_dual_source.csv generated by rebuild_replay_dual_source_labels_v3.py
and only adds:

  primary_*      = bowl1_*
  alternative_* = bowl2_*
  alternative_minus_primary_* = bowl2_minus_bowl1_*

This guarantees exact numerical consistency with the original v3 label script.
"""

import argparse
import csv
import json
from pathlib import Path


def read_csv(path):
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def write_csv(rows, path):
    if not rows:
        return
    fields = list(rows[0].keys())
    extras = sorted({k for r in rows for k in r.keys()} - set(fields))
    fields += extras
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def load_mapping(config_json, task_suite_name, task_key):
    cfg = json.loads(Path(config_json).read_text())
    return cfg[task_suite_name][task_key]


def copy_if_exists(row, src, dst):
    if src in row:
        row[dst] = row[src]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data_dir", required=True)
    ap.add_argument("--input_csv", default="summary_dual_source.csv")
    ap.add_argument("--output_csv", default="summary_object_pair.csv")
    ap.add_argument("--config_json", required=True)
    ap.add_argument("--task_suite_name", default="libero_spatial")
    ap.add_argument("--task_key", required=True)
    args = ap.parse_args()

    data_dir = Path(args.data_dir)
    mapping = load_mapping(args.config_json, args.task_suite_name, args.task_key)

    primary = mapping["primary_object"]
    alternative = mapping["alternative_object"]

    # Current LIBERO-spatial task1/3/8/9 mapping.
    if primary != "akita_black_bowl_1" or alternative != "akita_black_bowl_2":
        raise ValueError(
            "This wrapper only supports primary=bowl1 and alternative=bowl2. "
            f"Got primary={primary}, alternative={alternative}. "
            "For other mappings, extend the original dual-source label script instead."
        )

    rows = read_csv(data_dir / args.input_csv)
    out_rows = []

    for r in rows:
        out = dict(r)

        out["task_key_for_labels"] = args.task_key
        out["primary_object"] = primary
        out["alternative_object"] = alternative
        out["target_object"] = mapping.get("target_object", "")
        out["primary_role"] = mapping.get("primary_role", "")
        out["alternative_role"] = mapping.get("alternative_role", "")

        # bowl1 -> primary
        for k in list(r.keys()):
            if k.startswith("bowl1_"):
                out["primary_" + k[len("bowl1_"):]] = r[k]

        # bowl2 -> alternative
        for k in list(r.keys()):
            if k.startswith("bowl2_"):
                out["alternative_" + k[len("bowl2_"):]] = r[k]

        # bowl2_minus_bowl1 -> alternative_minus_primary
        for k in list(r.keys()):
            if k.startswith("bowl2_minus_bowl1_"):
                out["alternative_minus_primary_" + k[len("bowl2_minus_bowl1_"):]] = r[k]

        out_rows.append(out)

    out_path = data_dir / args.output_csv
    write_csv(out_rows, out_path)

    print("[saved]", out_path)
    print("rows:", len(out_rows))
    print("task_key:", args.task_key)
    print("primary:", primary)
    print("alternative:", alternative)


if __name__ == "__main__":
    main()